diff --git a/Makefile b/Makefile
index 3d3d5e4..ddc7f7c 100644
--- a/Makefile
+++ b/Makefile
@@ -13,18 +13,21 @@ ARCH= -gencode arch=compute_20,code=[sm_20,sm_21] \
 # ARCH=  -gencode arch=compute_52,code=compute_52
 
 VPATH=./src/
-EXEC=darknet
+EXEC=darknet.html
 OBJDIR=./obj/
 
-CC=gcc
+CC=emcc
 NVCC=nvcc 
-OPTS=-Ofast
-LDFLAGS= -lm -pthread 
+OPTS=-O2 --llvm-lto 1
+LDFLAGS= -lm -O2 --preload-file ./data --preload-file ./cfg --preload-file ./weights -s TOTAL_MEMORY=1073741824 -s ALLOW_MEMORY_GROWTH=1 -s INVOKE_RUN=0 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1
+# -s WASM=1 -s "BINARYEN_METHOD='native-wasm'" -s SIMD=0
+# -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=2
 COMMON= 
-CFLAGS=-Wall -Wfatal-errors 
+CFLAGS=-Wall -Wfatal-errors
 
 ifeq ($(DEBUG), 1) 
 OPTS=-O0 -g
+LDFLAGS+= -O0 -g -s ASSERTIONS=1
 endif
 
 CFLAGS+=$(OPTS)
