diff --git a/Makefile b/Makefile
index 3d3d5e4..44a5305 100644
--- a/Makefile
+++ b/Makefile
@@ -2,7 +2,6 @@ GPU=0
 CUDNN=0
 OPENCV=0
 DEBUG=0
-
 ARCH= -gencode arch=compute_20,code=[sm_20,sm_21] \
       -gencode arch=compute_30,code=sm_30 \
       -gencode arch=compute_35,code=sm_35 \
@@ -13,18 +12,17 @@ ARCH= -gencode arch=compute_20,code=[sm_20,sm_21] \
 # ARCH=  -gencode arch=compute_52,code=compute_52
 
 VPATH=./src/
-EXEC=darknet
+EXEC=darknet.html
 OBJDIR=./obj/
 
-CC=gcc
+CC=emcc
 NVCC=nvcc 
-OPTS=-Ofast
-LDFLAGS= -lm -pthread 
+OPTS=-O2 --llvm-lto 1
+LDFLAGS= -lm -O2 --preload-file ./data --preload-file ./cfg --preload-file ./weights -s TOTAL_MEMORY=1099511627776 -s INVOKE_RUN=0 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=2
 COMMON= 
-CFLAGS=-Wall -Wfatal-errors 
-
+CFLAGS=-Wall -Wfatal-errors -s SIMD=1
 ifeq ($(DEBUG), 1) 
-OPTS=-O0 -g
+OPTS=-O0 -g -s ASSERTIONS=1
 endif
 
 CFLAGS+=$(OPTS)